### PR TITLE
Add Laravel 9 compatibility

### PR DESCRIPTION
**Pull request by jdecool**
Laravel 9 has been published.

I'm interesting to use this package in my projects.

### CODE REVIEW

**Comment by VincentBean** [comment]
Thank you for the PR

**Comment by jdecool** [comment]
Hey @VincentBean do you plan to merge this PR ?

**Comment by VincentBean** [comment]
I thought I did already, thanks for the reminder :)

**Comment by jdecool** [comment]
Thanks !

**Pull request merged**
